name: Deploy to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NEXT_PUBLIC_API_BASE_URL: NEXT_PUBLIC_API_BASE_URL

on:
  push:
    branches:
      - main

jobs:
  deploy-to-vercel:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Import environment variables
        env:
          DEPLOY_ENV: ${{ secrets.DEPLOY_ENV }}
        run: |
          exec .github/scripts/import-deploy-env.sh

      - name: Bun Setup
        uses: oven-sh/setup-bun@v1

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
